// <auto-generated />
using KezsPillowShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KezsPillowShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200621154144_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KezsPillowShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Small",
                            Description = "Small Pillows"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Medium",
                            Description = "Medium-sized Pillows"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Large",
                            Description = "Large Pillows"
                        });
                });

            modelBuilder.Entity("KezsPillowShop.Models.Pillow", b =>
                {
                    b.Property<int>("PillowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPillowOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PillowId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pillows");

                    b.HasData(
                        new
                        {
                            PillowId = 1,
                            CategoryId = 1,
                            ImageThumbnailURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXsK2fq0Tqa8fE5rD1AxovFIHY_HveG4PlGilg0H-GSWpv0BYN&usqp=CAU",
                            ImageURL = "https://ae01.alicdn.com/kf/H1c61b06d8d0a4e6ab356c550559c47a4k/Ins-Fluffy-Pillow-Wool-Cushions-Fur-Cushion-Cover-Sofa-Long-Plush-Bed-Pillows-Christmas-Decorations-Christmas.jpg",
                            InStock = true,
                            IsPillowOfTheWeek = true,
                            LongDescription = "This pillow is fluffy",
                            Name = "Fluffy Pillow",
                            Price = 4.00m,
                            ShortDescription = "Fluffy"
                        },
                        new
                        {
                            PillowId = 2,
                            CategoryId = 3,
                            ImageThumbnailURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSWaBdPWH3paRAS4LQKhr36RjkeiRx3aYVTtgMhSgbzK5FPIieh&usqp=CAU",
                            ImageURL = "https://www.livelaughlove.co.uk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/l/lll_53_32.jpg",
                            InStock = false,
                            IsPillowOfTheWeek = false,
                            LongDescription = "This pillow is patchy",
                            Name = "Patchwork Pillow",
                            Price = 10.00m,
                            ShortDescription = "Patchy"
                        },
                        new
                        {
                            PillowId = 3,
                            CategoryId = 2,
                            ImageThumbnailURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS47efweL_I18knIGa3nLg0KGTeGlp_x6jf4rOaRvWVvs2PlaEz&usqp=CAU",
                            ImageURL = "https://i1.adis.ws/i/dm/30180876.jpg?$standardplayerdefault$&img404=noimagedefault",
                            InStock = true,
                            IsPillowOfTheWeek = true,
                            LongDescription = "This pillow is shaped like a heart",
                            Name = "Heart Pillow",
                            Price = 7.00m,
                            ShortDescription = "Hearty"
                        },
                        new
                        {
                            PillowId = 4,
                            CategoryId = 1,
                            ImageThumbnailURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSMdOkIfISIK2jYNoWsJVpmk0raK-rKlcTTRAeQpAwl0wHky_Xq&usqp=CAU",
                            ImageURL = "https://seoulify.net/wp-content/uploads/2017/11/40x30cm-Pusheen-Cat-Plush-Toys-Stuffed-Animal-Doll-Animal-Pillow-Toy-Pusheen-Cat-For-Kid-Kawaii-5.jpg",
                            InStock = true,
                            IsPillowOfTheWeek = false,
                            LongDescription = "This pillow is decorated with animals",
                            Name = "Animal Pillow",
                            Price = 4.00m,
                            ShortDescription = "Animalistic"
                        });
                });

            modelBuilder.Entity("KezsPillowShop.Models.Pillow", b =>
                {
                    b.HasOne("KezsPillowShop.Models.Category", "Category")
                        .WithMany("Pillow")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
